# Generated by Django 3.2.8 on 2021-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('email_text', models.TextField(verbose_name='Текст письма')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Окно для записи',
                'verbose_name_plural': 'Окна для записи',
                'ordering': ['created_at'],
            },
        ),
    ]
