# Generated by Django 3.2.8 on 2021-10-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'ordering': ['time'], 'verbose_name': 'Окно для записи', 'verbose_name_plural': 'Окна для записи'},
        ),
        migrations.AddField(
            model_name='tickets',
            name='email',
            field=models.EmailField(default='non@non.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Номер тел.'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Свободно'),
        ),
    ]
