# Generated by Django 3.2.8 on 2021-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211013_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='str_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='email',
            field=models.EmailField(default='x@x.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='phone',
            field=models.CharField(default='+7', max_length=12, verbose_name='Номер тел.'),
        ),
    ]
